# Generated by Django 3.0.3 on 2020-02-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(default='q', max_length=100),
        ),
    ]
